# Site wide configuration
title:
    en: Robert C. Gabriell
    es: Blog de Robert C. Gabriell
description:
    en: Stories of a busy-man in a busy-life
    es: Historias de una vida ajetreada
logo: bio-photo.jpg
url: https://www.gabriell.es
#url: https://localhost:4000
paginate_per_category: 10
paginate_root_category: es
comments: true
search: true

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-twitter-plugin
twitter:
  consumer_key: XRproIQHg20XHsgxocwpaqrKS
  consumer_secret: kGZQkJpoCiiLNWpQCho1HQx3Me4O5WOOXGYB4103iNBfahAVFF
  access_token: 105776582-MW8prZTjtSypt0jfTNFH0bpQNKPbzA44RwVz6jJD
  access_token_secret: JWqxRE88CepPhZII8295RjEqUzOEzGUGAEtyWtleIaWzV

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Languages
defaults:
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      path: es
    values:
      lang: es

# Site owner
owner:
  name: Robert C. Gabriell
  avatar: bio-photo.jpg
  email:
  disqus-shortname: 
  twitter: 
  facebook:
  github: 
  stackexchange:
  linkedin: 
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
